name: Deploy UI Preview

# Trigger on push to main or manual run
on:
  #push:
   # branches: [ main ]
  workflow_dispatch:

# Give workflow write access to repo
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Install Node
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies & build
      - run: npm install
      - run: npm run build

      # Optional: Check build folder
      - run: ls ./dist

      # Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist   # Change to ./build if your app outputs build folder
          force_orphan: true   # optional, forces update even if git thinks nothing changed
